/// Flutter icons Idea
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Idea
///      fonts:
///       - asset: fonts/Idea.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Idea {
  Idea._();

  static const _kFontFam = 'Idea';
  static const _kFontPkg = null;

  static const IconData icons8_idea = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
