/// Flutter icons News
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  News
///      fonts:
///       - asset: fonts/News.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class News {
  News._();

  static const _kFontFam = 'News';
  static const _kFontPkg = null;

  static const IconData icons8_news = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
