/// Flutter icons Share
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Share
///      fonts:
///       - asset: fonts/Share.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Share {
  Share._();

  static const _kFontFam = 'Share';
  static const _kFontPkg = null;

  static const IconData icons8_share = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
