/// Flutter icons Emergency
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Emergency
///      fonts:
///       - asset: fonts/Emergency.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Emergency {
  Emergency._();

  static const _kFontFam = 'Emergency';
  static const _kFontPkg = null;

  static const IconData warning = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
